import type { UseChatHelpers } from "@ai-sdk/react";
import { CopyIcon, CpuIcon, GlobeIcon } from "@phosphor-icons/react";
import React from "react";
import { toast } from "sonner";
import { formatTokens } from "~/lib/format-tokens";
import { getMessageContentFromParts } from "~/lib/get-message-content-from-parts";
import { isImageGenerationModel } from "~/lib/is-image-generation-model";
import { useAppearanceStore } from "~/stores/appearance-store";
import type { CustomUIMessage } from "~/types";
import AIGeneratedImages from "./ai-generated-images";
import AIResponseContent from "./ai-response-content";
import AIResponseReasoning from "./ai-response-reasoning";
import AIResponseSources from "./ai-response-sources";
import BranchOffButton from "./branch-off-button";
import ImageGenerationSkeleton from "./image-generation-skeleton";
import RetryModelDropdown from "./retry-model-dropdown";
import ThinkingIndicator from "./thinking-indicator";
import { Button } from "./ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "./ui/tooltip";

type Props = {
	message: CustomUIMessage;
	regenerate?: UseChatHelpers<CustomUIMessage>["regenerate"];
};

export default React.memo(function AssistantMessage(props: Props) {
	const { message, regenerate } = props;
	const showTokenUsage = useAppearanceStore((store) => store.showTokenUsage);
	const isImageMessage = isImageGenerationModel({
		modelId: message.metadata?.modelId,
		name: message.metadata?.modelName,
	});
	const hasRenderableParts = message.parts.some(
		(part) => part.type !== "step-start",
	);

	if (message.parts.length === 0 || (isImageMessage && !hasRenderableParts)) {
		return (
			<div className="px-3 lg:px-0">
				{isImageMessage ? <ImageGenerationSkeleton /> : <ThinkingIndicator />}
			</div>
		);
	}

	const messageContent = getMessageContentFromParts(message.parts);

	return (
		<div className="group space-y-6">
			<AIResponseReasoning
				messageContent={messageContent}
				messageId={message.id}
				parts={message.parts}
			/>
			<AIResponseContent
				messageContent={messageContent}
				messageId={message.id}
			/>
			<AIGeneratedImages parts={message.parts} />
			<AIResponseSources parts={message.parts} />

			{/* Message actions - visible on mobile, hover on desktop */}
			<div className="flex items-center gap-6 opacity-100 transition-opacity duration-200 md:opacity-0 md:group-hover:opacity-100">
				<div className="flex items-center gap-1">
					<Tooltip>
						<TooltipTrigger
							render={
								<Button
									onClick={async () => {
										await navigator.clipboard.writeText(messageContent);
										toast.success("Copied to clipboard");
									}}
									size="icon"
									variant="ghost"
								/>
							}
						>
							<CopyIcon />
						</TooltipTrigger>
						<TooltipContent>Copy to clipboard</TooltipContent>
					</Tooltip>

					<BranchOffButton message={message} />

					{regenerate && (
						<RetryModelDropdown message={message} regenerate={regenerate} />
					)}

					<span className="text-xs text-muted-foreground">
						{message.metadata?.modelName}
					</span>

					{message.parts.filter(
						(part) =>
							part.type === "source-document" || part.type === "source-url",
					).length > 0 && (
						<Tooltip>
							<TooltipTrigger>
								<GlobeIcon className="size-3 text-muted-foreground" />
							</TooltipTrigger>
							<TooltipContent>
								Content was generated by web search
							</TooltipContent>
						</Tooltip>
					)}
				</div>

				{showTokenUsage && message.metadata?.totalTokens && (
					<div className="flex items-center gap-1 text-xs text-muted-foreground">
						<CpuIcon className="size-4" />
						{formatTokens(message.metadata?.totalTokens)}
					</div>
				)}
			</div>
		</div>
	);
});
